package com.sandbox.util.kafka;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

/**
 * Enum defining Kafka topics and their associated default consumer group IDs.
 */
@Getter
@RequiredArgsConstructor
public enum KafkaTopicInfo {

    /**
     * Topic for random log messages generated by the Foo module.
     */
    FOO_LOGGING("FOO_LOGGING_TOPIC", "foo-log-consumer-group");

    private final String topicName;
    private final String consumerGroupId;

} 