FROM amazoncorretto:21-alpine-jdk

# Set the maintainer
MAINTAINER durszlak

# Set the working directory
WORKDIR /app

# Install bash in Alpine
RUN apk add --no-cache bash

# Copy the jar file into the container
COPY target/Host-0.0.1-SNAPSHOT.jar /app/Host-0.0.1-SNAPSHOT.jar

# Set bash as the default shell and run the Java application
ENTRYPOINT ["/bin/bash", "-c", "java -jar /app/Host-0.0.1-SNAPSHOT.jar"]
