server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://db:5432/${POSTGRES_DB}"
    username: "${POSTGRES_USER}"
    password: "${POSTGRES_PASSWORD}"

  liquibase:
    change-log: "classpath:liquibase-changeLog.xml"

  jpa:
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

files:
  baseDir: "/app/data/Data.txt"

data:
  exampleUri: "https://jsonplaceholder.typicode.com/posts"
  passphraseUrl: "http://fooservice:8090/passphrase"

audit:
  patterns: '/**'