--liquibase formatted sql

--changeset durszlak:1
CREATE TABLE COUNTRIES
(
    COUNTRY_ID BIGSERIAL PRIMARY KEY,
    COUNTRY    VARCHAR(50) NOT NULL,
    CODE       VARCHAR(10) NOT NULL,
    INS_TIME   TIMESTAMP DEFAULT CURRENT_DATE,
    VERSION    INTEGER NOT NULL
);

--changeset durszlak:2
CREATE INDEX COUNTRIES_CODE_INDEX ON COUNTRIES(CODE);

--changeset durszlak:3
INSERT INTO COUNTRIES(COUNTRY, CODE, VERSION) VALUES ('POLAND', '01', 0);
INSERT INTO COUNTRIES(COUNTRY, CODE, VERSION) VALUES ('GERMANY', '02', 0);
INSERT INTO COUNTRIES(COUNTRY, CODE, VERSION) VALUES ('UK', '03', 0);
INSERT INTO COUNTRIES(COUNTRY, CODE, VERSION) VALUES ('USA', '04', 0);
INSERT INTO COUNTRIES(COUNTRY, CODE, VERSION) VALUES ('HOLLAND', '05', 0);
INSERT INTO COUNTRIES(COUNTRY, CODE, VERSION) VALUES ('ISRAEL', '06', 0);
INSERT INTO COUNTRIES(COUNTRY, CODE, VERSION) VALUES ('FRANCE', '07', 0);
INSERT INTO COUNTRIES(COUNTRY, CODE, VERSION) VALUES ('SPAIN', '08', 0);
INSERT INTO COUNTRIES(COUNTRY, CODE, VERSION) VALUES ('FINLAND', '09', 0);
INSERT INTO COUNTRIES(COUNTRY, CODE, VERSION) VALUES ('RUSSIA', '10', 0);

--changeset durszlak:4
INSERT INTO COUNTRIES(COUNTRY, CODE, VERSION) VALUES ('SLOVAKIA', '11', 0);
INSERT INTO COUNTRIES(COUNTRY, CODE, VERSION) VALUES ('CHILE', '12', 0);