FROM amazoncorretto:21-alpine-jdk

# Set the maintainer
MAINTAINER durszlak

# Set the working directory
WORKDIR /app

# Install bash in Alpine
RUN apk add --no-cache bash

# Copy the jar file into the container
COPY target/Server-0.0.1-SNAPSHOT.jar /app/server.jar

# Set bash as the default shell and run the Java application with JAVA_OPTS
ENTRYPOINT ["/bin/bash", "-c", "java $JAVA_OPTS -jar /app/server.jar"]
